name:        inline-js-example
version:     0.0.1.0

data-files:         jsbits/node_modules/left-pad/index.js

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wpartial-fields
- -Wredundant-constraints
- -fhide-source-paths

dependencies:
- aeson
- base >=4.11 && < 5
- bytestring
- file-embed
- filepath
- inline-js-core
- template-haskell
- unliftio

library:
  source-dirs: src

_exe-ghc-options:        &exe-ghc-options
  - -threaded
  - -rtsopts
  - -with-rtsopts=-N

executables:
  main:
    source-dirs:         app
    main:                Main.hs
    other-modules:       ""
    ghc-options:         *exe-ghc-options
    dependencies:
      - inline-js-example

tests:
  test:
    source-dirs:         test
    main:                Main.hs
    other-modules:       ""
    ghc-options:         *exe-ghc-options
    dependencies:
      - inline-js-example
      - tasty
      - tasty-hunit
      - tasty-quickcheck

